# Generated by Django 6.0 on 2026-01-21 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Titulo"
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="entradas/%Y/%m/%d",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha alta"),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.categoria"
                    ),
                ),
            ],
        ),
    ]
