# Generated by Django 6.0 on 2026-01-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_entrada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["id"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="entrada",
            options={
                "ordering": ["id"],
                "verbose_name": "Entada",
                "verbose_name_plural": "Entradas",
            },
        ),
        migrations.AlterModelTable(
            name="categoria",
            table="categorias",
        ),
        migrations.AlterModelTable(
            name="entrada",
            table="entradas",
        ),
    ]
